# Generated by Django 3.1.7 on 2021-04-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210402_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueidtable',
            name='uniqueid',
            field=models.CharField(default='f8337436-1d52-4624-af29-7222ff5d90c6', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
