# Generated by Django 3.1.7 on 2021-04-02 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueidTable',
            fields=[
                ('uniqueid', models.CharField(default='53399fb2-b80a-4d0f-b0c3-2410e8c1d90a', editable=False, max_length=50, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active_state', models.CharField(default='active', max_length=10)),
                ('hits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
                ('uniqueid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.uniqueidtable')),
            ],
        ),
    ]
