# Generated by Django 3.1.7 on 2021-04-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uniqueidtable',
            name='uniqueid',
            field=models.CharField(default='73fd610c-6939-4294-8097-54aadb006f06', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
